### ISSUE TITLE
Exporting Molecular Fingerprints of Compounds

### ISSUE THREAD

**Issue by Jasmin-Zeng** [samgoldman97/mist#7]
Hello, Sam. Your work is highly meaningful, but I would like to inquire if it is possible to export molecular fingerprints for the MS/MS spectra as well as the molecular fingerprints of compounds with known structures. If you could clarify these doubts for me, I would greatly appreciate it.

**Comment by samgoldman97** [comment]
Hi Alan, 
Thanks for your interest. Can you please clarify the question slightly to help me understand what you mean by "compounds with known structures"? 

This notebook https://github.com/samgoldman97/mist/blob/main/notebooks/mist_demo.ipynb showcases how to do fingerprint prediction for exporting MS/MS spectra. To also export fingerprints for smiles strings, you can use RDKit directly, or use our featurizer wrappers:

```
from mist.data import featurizers
from mist.data import data

smiles = "CCC"
mol = data.Mol.MolFromSmiles(smiles)
fp_featurizer = featurizers.FingerprintFeaturizer(fp_names=["morgan4096"])
fp_output = fp_featurizer.featurize(mol)
```


Best,
Sam

**Comment by Jasmin-Zeng** [comment]
Hello! I'm glad to see your response. In my question, "compounds with known structures" refers to the compounds used during model training, and their MS/MS spectra and molecular fingerprints are known in advance.

**Comment by samgoldman97** [comment]
I see. I don't have these on hand for quick export, but if you follow the repository instructions to download the public training data, you should be able to export these as well. You can export these directly by running the model as described above.

**Comment by Jasmin-Zeng** [comment]
![20230704205127](https://github.com/samgoldman97/mist/assets/127714884/ddc8cc60-29ba-4007-94b3-ecde86ee9e12)
Taking this image as an example, I would like to export the substructures corresponding to these molecular fingerprints, along with the numerical values of the fingerprints. I noticed that the demo you provided already allows for exporting the fingerprint values, but I am unsure how to export the corresponding chemical substructures of these fingerprints. I hope I have made my question clear.

**Comment by samgoldman97** [comment]
Oh i think I see. If i understand correctly, you want to understand what each fingerprint bit means? 

One challenge is that these are hashed circular fingerprints, so it's not a unique map from fingerprint bits to structural motifs. While it may be a little bit of extra work, you may be able to back out some substructure options for each prediction by fingerprinting the entire training set and extracting motifs that led to each bit, using something like this: https://www.rdkit.org/docs/GettingStartedInPython.html#explaining-bits-from-fingerprints

This is admittedly a shortcoming of the fingerprints we use vs. substructure fingerprints; we opted for Morgan fingerprints here because of how widely used and publicly supported they are.

**Comment by Jasmin-Zeng** [comment]
ok, I see. Thank you very much for your response. I will give it a try.
